{
  self,
  inputs,
  ...
}: {
  flake.nixosModules.navidrome = {
    pkgs,
    lib,
    config,
    ...
  }: {
    # declaration of the actual navidrome service itself
    services.navidrome = {
      enable = true;
      openFirewall = true; # opens port 4533 for navidrome server to be accessed over lan
      environmentFile = config.sops.secrets.navidrome.path;
      settings = {
        Address = "0.0.0.0";
        EnableInsightsCollector = true;

        MusicFolder = "/srv/storage/media/music";

        BaseUrl = "https://navidrome.myles.onl";

        EnableSharing = true;
        EnableGravatar = true;

        Agents = "audiomuseai,deezer,lastfm,listenbrainz";

        LastFM.Enabled = true;
        LastFM.Language = "en";

        Plugins.Enabled = true;
        Plugins.AutoReload = true;
      };
    };

    # finally I will add the navidrome user generated by navidrome to the group "media" so it can access the external folders it needs to
    users.users.navidrome.extraGroups = ["media"];
  };
}
