keys:
  - &myles age12y9t37jpa0fk25x6g5mpu7lx6nlxe8agayrzxfanz25rdal0xsxs3eg74u
  - &desktop age1h3ujq0fl5jlaeac7m35l4nvr9q48whesyl9ngymasxq6hlwv7qyslukauc
  - &laptop age1h3ujq0fl5jlaeac7m35l4nvr9q48whesyl9ngymasxq6hlwv7qyslukauc
  - &server age1fsrx4yeulwv792tz8ahmegjp3c7ga7fr0cw5l26hqd5c4u98quzq0wlthj
  - &wsl age1j6hhgvtcvae7c8p7yss808zgyxzzat2wkm2acxvkd6h6qevx8fgqyunlq0

creation_rules:
  - path_regex: hosts/laptop/secrets\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *myles
      - *laptop
  - path_regex: hosts/server/secrets\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *myles
      - *server
  - path_regex: hosts/wsl/secrets\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *myles
      - *wsl
  - path_regex: hosts/desktop/secrets\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *myles
      - *desktop
