services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - VERSION=${RUNTIME}
    ports:
      - 32400:32400
    volumes:
      - ${DATA}/plex:/config
      - ${STORAGE}:/data
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA}/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
