{
  self,
  inputs,
  ...
}: {
  flake.nixosModules.navidrome = {
    pkgs,
    lib,
    config,
    ...
  }: {
    # declaration of the actual navidrome service itself
    services.navidrome = {
      enable = true;
      openFirewall = true; # opens port 4533 for navidrome server to be accessed over lan
      settings = {
        EnableInsightsCollector = true;

        MusicFolder = "/srv/storage/media/music";
        DataFolder = "/srv/data/navidrome/data";

        BaseUrl = "https://navidrome.myles.onl";

        EnableSharing = true;
        EnableGravatar = true;

        Agents = "audiomuseai,lastfm,deezer";

        LastFM.Enabled = true;
        LastFM.ApiKey = "$(cat ${config.sops.secrets."navidrome/lastfm/apikey".path})";
        LastFM.Secret = "$(cat ${config.sops.secrets."navidrome/lastfm/secret".path})";
        LastFM.Language = "en";

        Plugins.Enabled = true;
        Plugins.AutoReload = true;
        Plugins.Folder = "/srv/data/navidrome/plugins/";
      };
    };

    # make sure that navidrome exists and is of the correct permissions
    systemd.tmpfiles.settings = {
      "10-navidrome" = {
        "${config.services.navidrome.settings.DataFolder}" = {
          d = {
            mode = "0770";
            user = "navidrome";
            group = "navidrome";
          };
          Z = {
            mode = "0770";
            user = "navidrome";
            group = "navidrome";
          };
        };
      };
    };

    # finally I will add the navidrome user generated by navidrome to the group "media" so it can access the external folders it needs to
    users.users.navidrome.extraGroups = [ "media" ];
  };
}
